Portal.Admininstration/Portal.AdminSystem/Models/ExecClientUsergroups.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;

namespace Portal.AdminSystem.Models
{
   public class ExecClientUsergroups
    {   
        [Display(Name = "UsergroupID")]
        public int UsergroupID { get; set; }

        [Display(Name = "Description")]
        public string Description { get; set; }

        [Display(Name = "Trial Period")]
        public int TrialPeriod { get; set; }

        [Display(Name = "Principal")]
        public bool Principal { get; set; }

        [Display(Name = "Email")]
        public string Email { get; set; }

        [Display(Name = "Priority")]
        public int Priority { get; set; }

        [Display(Name = "Grouping")]
        public int Grouping { get; set; }

        [Display(Name = "Display Name")]
        public string DisplayName { get; set; }

    }

    public class SearchExecClient
    {
        [Display(Name = "Client Name")]
        public string SearchDescription { get; set; }

        public List<ExecClientUsergroups> ExecClientUsergroupResults { get; set; } = new List<ExecClientUsergroups>();
    }
}

Portal.Admininstration/Portal.AdminSystem/Controllers/ExecClientUsergroupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Portal.AdminSystem.Models;
using System.Configuration;

namespace Portal.AdminSystem.Controllers
{
    [Authorize]
    public class ExecClientUsergroupsController : Controller
    {
        readonly static string connectionString = ConfigurationManager.ConnectionStrings["ExecCareConnection"].ConnectionString;
        ExecClientUsergroupsLogic execClientUsergroupsLogic = new ExecClientUsergroupsLogic(connectionString);
        BusinessLogic businessLogic = new BusinessLogic();

        public ActionResult Index()
        {
            return View(businessLogic.PortalRetrieveExecClientUsergrops());
        }

        public ActionResult Details(int id)
        {
            return View(execClientUsergroupsLogic.Find(id));
        }

        public ActionResult ExecClient()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ExecClient(ExecClientUsergroups execClientUsergroups)
        {
            try
            {
                businessLogic.CreateExecClientUsergroups(execClientUsergroups);
                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            return View(execClientUsergroupsLogic.Find(id));
        }
        [HttpPost]
        public ActionResult Edit(int id, ExecClientUsergroups execClientUsergroups)
        {
            try
            {
                execClientUsergroupsLogic.UpdateExecUsergroup(execClientUsergroups);
                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult SearchExecClientUsergroup()
        {
            SearchExecClient searchExecClient = new Models.SearchExecClient();
            searchExecClient.ExecClientUsergroupResults = new List<ExecClientUsergroups>();
            return View(searchExecClient);
        }

        [HttpPost]
        public ActionResult SearchExecClientUsergroup(SearchExecClient searchExecClient)
        {
            searchExecClient.ExecClientUsergroupResults = businessLogic.RetrieveExecClientUsergroupResults(searchExecClient).ToList();
            return View(searchExecClient);
        }
    }
}

Portal.Admininstration/Portal.AdminSystem/Views/ExecClientUsergroups/Details.cshtml
@model Portal.AdminSystem.Models.ExecClientUsergroups

@{
    ViewBag.Title = "Client Usergroup Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="Container2">
    <div class="left">
        <img src="~/Images/Execcare.png" width:"100%"style="display: block;" />
        <h4 class="greyPortal"><strong>@ViewBag.Title</strong></h4>
    </div>
    <p class="right">
        <img src="~/Images/healthinsite.png" width:"100%"style="display: block;" />
    </p>
    <br />
    <br />
    <hr class="exechr" />
    <dl class="dl-horizontal">
        <dt class="greyPortal">
            @Html.DisplayNameFor(model => model.UsergroupID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UsergroupID)
        </dd>

        <dt class="greyPortal">
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt class="greyPortal">
            @Html.DisplayNameFor(model => model.TrialPeriod)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TrialPeriod)
        </dd>

        <dt class="greyPortal">
            @Html.DisplayNameFor(model => model.Principal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Principal)
        </dd>

        <dt class="greyPortal">
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt class="greyPortal">
            @Html.DisplayNameFor(model => model.Priority)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Priority)
        </dd>

        <dt class="greyPortal">
            @Html.DisplayNameFor(model => model.Grouping)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grouping)
        </dd>

        <dt class="greyPortal">
            @Html.DisplayNameFor(model => model.DisplayName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DisplayName)
        </dd>

    </dl>
    <p>
        <input type="button" value="<<Back" class="portalbtn btn-default" onclick="location.href='@Url.Action("SearchExecClientUsergroup")'; " />
    </p>
</div>
<br />

Portal.Admininstration/Portal.AdminSystem/Views/ExecClientUsergroups/Edit.cshtml
@model Portal.AdminSystem.Models.ExecClientUsergroups

@{
    ViewBag.Title = "Update Client Usergroup";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
            <div class="Container2">
                <div class="left">
                    <img src="~/Images/Execcare.png" width:"100%"style="display: block;" />
                    <h4 class="greyPortal"><strong>@ViewBag.Title</strong></h4>
                </div>
                <p class="right">
                    <img src="~/Images/healthinsite.png" width:"100%"style="display: block;" />
                </p>
                <br />
                <br />
                <hr class="exechr" />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.UsergroupID)
                @Html.HiddenFor(model => model.Principal)
                @Html.HiddenFor(model => model.Email)
                @Html.HiddenFor(model => model.Priority)
                @Html.HiddenFor(model => model.Grouping)
                @Html.HiddenFor(model => model.DisplayName)
                <div class="form-group greyPortal">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group greyPortal">
                    @Html.LabelFor(model => model.TrialPeriod, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TrialPeriod, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TrialPeriod, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group greyPortal">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Update" class="portalbtn btn-default" />
                        <input type="button" id="cancel" value="Cancel" class="portalbtn btn-default" onclick="location.href='@Url.Action("Index","Home")'; " />
                        <input type="button" value="<<Back" class="portalbtn btn-default" onclick="location.href='@Url.Action("SearchExecClientUsergroup")'; " />
                     </div>
                </div>
            </div>
        </div>
}

<br />

Portal.Admininstration/Portal.AdminSystem/Views/ExecClientUsergroups/ExecClient.cshtml
@model Portal.AdminSystem.Models.ExecClientUsergroups

@{
    ViewBag.Title = "Client Usergroup";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <div class="Container2">
            <div class="left">
                <img src="~/Images/Execcare.png" width:"100%"style="display: block;" />
                <h4 class="greyPortal"><strong>@ViewBag.Title</strong></h4>
            </div>
            <p class="right">
                <img src="~/Images/healthinsite.png" width:"100%"style="display: block;" />
            </p>
            <br />
            <br />
            <hr class="exechr" />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group greyPortal">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Submit" class="portalbtn btn-default" />
                    <input type="reset" value="Reset" class="portalbtn btn-default" />
                    <input type="button" id="cancel" value="Cancel" class="portalbtn btn-default" onclick="location.href='@Url.Action("Index","Home")'; " />
                </div>
            </div>
        </div>
        </div>
}
<br />

Portal.Admininstration/Portal.AdminSystem/Views/ExecClientUsergroups/Index.cshtml
@model IEnumerable<Portal.AdminSystem.Models.ExecClientUsergroups>

@{
    ViewBag.Title = "Client Usergroups";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="Container2">
    <div class="left">
        <img src="~/Images/Execcare.png" width:"100%"style="display: block;" />
        <h4 class="greyPortal"><strong>@ViewBag.Title</strong></h4>
    </div>
    <p class="right">
        <img src="~/Images/healthinsite.png" width:"100%"style="display: block;" />
    </p>
    <br />
    <br />
    <hr class="exechr" />
    <table class="table">
        <tr class="redPortal">
            <th>
                @Html.DisplayNameFor(model => model.UsergroupID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TrialPeriod)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Principal)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.UsergroupID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TrialPeriod)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Principal)
                </td>           
            </tr>
        }

    </table>
    </div>
<br />

Portal.Admininstration/Portal.AdminSystem/Views/ExecClientUsergroups/SearchExecClientUsergroup.cshtml
@model Portal.AdminSystem.Models.SearchExecClient
@using GridMvc.Html
@{
    ViewBag.Title = "Search Client Usergroups";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
            <div class="Container2">
                <div class="left">
                    <img src="~/Images/Execcare.png" width:"100%"style="display: block;" />
                    <h4 class="greyPortal"><strong>@ViewBag.Title</strong></h4>
                </div>
                <p class="right">
                    <img src="~/Images/healthinsite.png" width:"100%"style="display: block;" />
                </p>
                <br />
                <br />
                <hr class="exechr" />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group greyPortal">
                    @Html.LabelFor(model => model.SearchDescription, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.SearchDescription, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SearchDescription, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Search" class="portalbtn btn-default" />
                        <input type="button" id="cancel" value="Cancel" class="portalbtn btn-default" onclick="location.href='@Url.Action("Index","Home")'; " />
                        <input type="button" value="Client Usergroup" class="portalbtn btn-default" onclick="location.href='@Url.Action("ExecClient","ExecClientUsergroups")'; " />
                    </div>
                </div>
            </div>
        </div>
            <div class="Container2">
                @Html.Grid(Model.ExecClientUsergroupResults).Columns(columns =>
   {
       columns.Add(m => m.UsergroupID)
       .Titled("")
       .Sanitized(false)
       .Encoded(false)
       .RenderValueAs(u =>
    @<b>
        @Html.ActionLink("View", "Details", new { id = u.UsergroupID }) |
        @Html.ActionLink("Update", "Edit", new { id = u.UsergroupID })
    </b>);
       columns.Add(c => c.Description).Titled("Description");
       columns.Add(c => c.TrialPeriod).Titled("Trial Period");
       columns.Add(c => c.Principal).Titled("Principal");

   }).WithPaging(50).Sortable(false).Selectable(true)

            </div>
            }
            <script>

                $(function () {
                    pageGrids.ordersGrid.onRowSelect(function (e) {
                        alert(e.row.UsergroupID);
                    });
                });
            </script>
            @section Scripts {
                @Scripts.Render("~/bundles/jqueryval")
            }